services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'shorturl'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgrespw'
    volumes: 
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      
    environment:
      POSTGRES_DB: 'shorturl'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgrespw'
    ports:
      - "8080:8080"

volumes:
  db:
    driver: local